import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import useTranslation from "next-translate/useTranslation";
import { useRouter } from "next/router";
import { useEffect } from "react";
import { useSelector, useDispatch } from 'react-redux'

const Home = (): any => {

  const { t } = useTranslation();
  
  const { locales, asPath, locale }: any = useRouter();

  const state = useSelector(state => state.user)
  const dispatch = useDispatch();

  useEffect(() => {
    document.documentElement.dir = locale == "ar" ? "rtl" : "ltr";
  }, [locale]);

  return (
    <div className="home">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container pt-xl">
        <div className="row">
          <div className="col-lg-6 col-12">
            <p>Home</p>
            <Link href="/about">
              <a>About</a>
            </Link>
            <br />
            <Link href="/auth/google" locale={false}>
              <a>Login with google</a>
            </Link>
            <br />
            {locales.map((item: any, index: any) => (
              <div key={index}>
                <Link href={asPath} locale={item}>
                  <a> {item}</a>
                </Link>
              </div>
            ))}
            <p>{t("common:test")}</p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Home;
